DROP TABLE IF EXISTS tb_role;

CREATE TABLE tb_role (
  id INT IDENTITY NOT NULL PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS tb_user_team_role;

CREATE TABLE tb_user_team_role (
  id INT IDENTITY NOT NULL PRIMARY KEY,
  user_id VARCHAR(50) NOT NULL,
  team_id VARCHAR(50) NULL,
  role_id INT NULL
);

